# Generated by Django 5.0.4 on 2024-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_created_at_remove_user_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Contributor')], default=2),
        ),
    ]
