# Generated by Django 5.0.4 on 2024-04-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
