# Generated by Django 5.0.4 on 2024-04-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(choices=[(1, 'Application'), (2, 'Screening'), (3, 'For Review'), (4, 'Interviewing'), (5, 'Trial Test')], default=1),
        ),
        migrations.DeleteModel(
            name='TicketProgress',
        ),
    ]
