# Generated by Django 5.0.4 on 2024-04-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='job_position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.jobposition'),
        ),
    ]
