# Generated by Django 5.0.4 on 2024-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tech_stacks',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tech_stacks',
            field=models.ManyToManyField(to='tickets.techstack'),
        ),
    ]
