# Generated by Django 5.0.4 on 2024-04-24 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_progress_delete_ticketprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.jobposition'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(choices=[(1, 'Application'), (2, 'Screening'), (3, 'For Review'), (4, 'Interviewing'), (5, 'Trial Test'), (6, 'Passed'), (7, 'Pooled'), (8, 'Withdrew'), (9, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tech_stacks',
            field=models.ManyToManyField(related_name='tickets', to='tickets.techstack'),
        ),
    ]
