# Generated by Django 5.0.4 on 2024-04-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_jobposition_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.jobposition'),
        ),
    ]
