# Generated by Django 5.0.4 on 2024-04-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketprogress',
            name='progress_id',
        ),
        migrations.AddField(
            model_name='ticketprogress',
            name='progress',
            field=models.IntegerField(choices=[(1, 'Application'), (2, 'Screening'), (3, 'For Review'), (4, 'Interviewing'), (5, 'Trial Test')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.comment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tech_stacks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.techstack'),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
