# Generated by Django 5.0.4 on 2024-04-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticketprogress_progress_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
